version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:463470956417:task-definition/my-td:2"  # ECS Task Definition ARN
        LoadBalancerInfo:
          ContainerName: "ngnix"  # Container name in ECS Task Definition
          ContainerPort: 80  # Port the container listens
